### ISSUE TITLE
Middleware with slim framework

### ISSUE THREAD

**Issue by gohelkiran30** [Ecodev/graphql-upload#4]
does UploadMiddleware works with slim middlework?

I have added this middleware to slim using
$app->add(new UploadMiddleware());

but it throws a below error

```
[22-Aug-2018 05:52:33] WARNING: [pool www] child 98 said into stderr: "RuntimeException: {} is not resolvable in /var/www/html/php/vendor/slim/slim/Slim/CallableResolver.php:104"
[22-Aug-2018 05:52:33] WARNING: [pool www] child 98 said into stderr: "Stack trace:"
[22-Aug-2018 05:52:33] WARNING: [pool www] child 98 said into stderr: "#0 /var/www/html/php/vendor/slim/slim/Slim/CallableResolver.php(56): Slim\CallableResolver->assertCallable(Object(GraphQL\Upload\UploadMiddleware))"
[22-Aug-2018 05:52:33] WARNING: [pool www] child 98 said into stderr: "#1 /var/www/html/php/vendor/slim/slim/Slim/CallableResolverAwareTrait.php(45): Slim\CallableResolver->resolve(Object(GraphQL\Upload\UploadMiddleware))"
[22-Aug-2018 05:52:33] WARNING: [pool www] child 98 said into stderr: "#2 /var/www/html/php/vendor/slim/slim/Slim/DeferredCallable.php(36): Slim\DeferredCallable->resolveCallable(Object(GraphQL\Upload\UploadMiddleware))"
[22-Aug-2018 05:52:33] WARNING: [pool www] child 98 said into stderr: "#3 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))"
[22-Aug-2018 05:52:33] WARNING: [pool www] child 98 said into stderr: "#4 /var/www/html/php/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))"
[22-Aug-2018 05:52:33] WARNING: [pool www] child 98 said into stderr: "#5 /var/www/html/php/vendor/tuupola/callable-handler/src/CallableHandler.php(34): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))"
```

**Comment by PowerKiKi** [comment]
This lib is a PSR-15 middleware implementation. It [seems like Slim middlewares are not PSR-15](https://www.slimframework.com/docs/v3/concepts/middleware.html) compatible. You'll have to refer to Slim community to find a way to bridge Slim middleware with PSR-15 middleware. Maybe something similar as https://github.com/Ecodev/graphql-upload/issues/1#issuecomment-362064036.

**Comment by PowerKiKi** [comment]
Also see https://github.com/Ecodev/graphql-upload/commit/885797dd00270c3b013fa10bfc300089d75a3a10 and https://github.com/slimphp/Slim/issues/2050
